"""Required release hygiene paths."""

from __future__ import annotations

REQUIRED_RELEASE_DOCS = [
    "README.md",
    "docs/09_roadmap.md",
    "docs/12_release_and_portfolio_plan.md",
    "docs/17_sprint_plans.md",
    "docs/18_delivery_process.md",
    "docs/06_safety_and_sandboxing.md",
]

REQUIRED_RELEASE_ARTIFACTS = [
    "experiments/index.md",
    "experiments/index.json",
    "experiments/index.html",
    "experiments/failure_report.md",
    "experiments/failure_report.json",
    "experiments/demo_readiness.md",
    "experiments/demo_readiness.json",
    "experiments/calibration_readiness.md",
    "experiments/calibration_readiness.json",
    "experiments/live_calibration_plan.md",
    "experiments/live_calibration_plan.json",
    "experiments/launch_blockers.md",
    "experiments/launch_blockers.json",
    "experiments/public_issue_corpus_v1/corpus_report.md",
    "experiments/public_issue_corpus_v1/corpus_summary.json",
    "experiments/public_issue_corpus_v1/repo_preflight_report.md",
    "experiments/public_issue_corpus_v1/repo_preflight_summary.json",
    "experiments/public_issue_corpus_v1/context_preview_report.md",
    "experiments/public_issue_corpus_v1/context_preview_summary.json",
    "experiments/public_issue_corpus_v1/materialized_task_report.md",
    "experiments/public_issue_corpus_v1/materialized_task_summary.json",
    "experiments/public_issue_corpus_v1/materialized_task_validation_report.md",
    "experiments/public_issue_corpus_v1/materialized_task_validation_summary.json",
    "experiments/public_issue_corpus_v1/materialized_run_readiness_report.md",
    "experiments/public_issue_corpus_v1/materialized_run_readiness_summary.json",
    "experiments/public_issue_corpus_v1/focused_test_plan_report.md",
    "experiments/public_issue_corpus_v1/focused_test_plan_summary.json",
    "experiments/public_issue_corpus_v1/focused_test_run_report.md",
    "experiments/public_issue_corpus_v1/focused_test_run_summary.json",
    "experiments/public_issue_corpus_v1/focused_test_diagnosis_report.md",
    "experiments/public_issue_corpus_v1/focused_test_diagnosis_summary.json",
    "experiments/public_issue_corpus_v1/focused_test_setup_plan_report.md",
    "experiments/public_issue_corpus_v1/focused_test_setup_plan_summary.json",
    "experiments/public_issue_corpus_v1/focused_test_setup_readiness_report.md",
    "experiments/public_issue_corpus_v1/focused_test_setup_readiness_summary.json",
    "experiments/public_issue_corpus_v1/focused_test_setup_execution_report.md",
    "experiments/public_issue_corpus_v1/focused_test_setup_execution_summary.json",
    "experiments/public_issue_corpus_v1/focused_test_setup_validation_report.md",
    "experiments/public_issue_corpus_v1/focused_test_setup_validation_summary.json",
    "experiments/public_issue_corpus_v1/public_issue_reproduction_plan_report.md",
    "experiments/public_issue_corpus_v1/public_issue_reproduction_plan_summary.json",
    "experiments/public_issue_corpus_v1/public_issue_failure_signal_discovery_report.md",
    "experiments/public_issue_corpus_v1/public_issue_failure_signal_discovery_summary.json",
    "experiments/public_issue_corpus_v1/public_issue_reproduction_spec_validation_report.md",
    ("experiments/public_issue_corpus_v1/public_issue_reproduction_spec_validation_summary.json"),
    "experiments/public_issue_corpus_v1/public_issue_reproduction_execution_report.md",
    "experiments/public_issue_corpus_v1/public_issue_reproduction_execution_summary.json",
    "experiments/public_issue_corpus_v1/public_issue_repair_readiness_report.md",
    "experiments/public_issue_corpus_v1/public_issue_repair_readiness_summary.json",
    "experiments/public_issue_corpus_v1/public_issue_repair_attempt_report.md",
    "experiments/public_issue_corpus_v1/public_issue_repair_attempt_summary.json",
    "experiments/demo_script.md",
    "experiments/demo_script.json",
    "experiments/environment_readiness.md",
    "experiments/environment_readiness.json",
    "experiments/quality_gate.md",
    "experiments/quality_gate.json",
    "experiments/project_status.md",
    "experiments/project_status.json",
    "experiments/final_evaluation.md",
    "experiments/final_evaluation.json",
    "experiments/delivery_audit.md",
    "experiments/delivery_audit.json",
]


__all__ = ["REQUIRED_RELEASE_ARTIFACTS", "REQUIRED_RELEASE_DOCS"]
