from __future__ import annotations

from importlib.util import find_spec
from pathlib import Path
from typing import Any

from patchsmith.patching import PatchSafetyError
from patchsmith.planning import HeuristicRepairPlanner, RepairPlanner
from patchsmith.runtime.core import (
    AgentResult,
    AgentTask,
    _apply_plan,
    _no_patch_result,
    _plan_or_planner_metadata,
    _prepare_planner_for_task,
)


class DeepAgentsRuntime:
    """Dependency-gated DeepAgents adapter behind the shared runtime boundary.

    The real `deepagents` package is optional. Local seeded evals use the same
    bounded planner/edit contract as other runtimes while emitting DeepAgents
    scaffold events for comparison. This keeps the adapter measurable without
    requiring live model credentials or installing the package globally.
    """

    def __init__(self, planner: RepairPlanner | None = None) -> None:
        self.planner = planner or HeuristicRepairPlanner()

    def run(self, task: AgentTask) -> AgentResult:
        repo_path = Path(task.repo_path)
        package_available = find_spec("deepagents") is not None
        mode = "package_available" if package_available else "compatibility_mode"
        _prepare_planner_for_task(self.planner, task)
        trace: list[dict[str, Any]] = [
            {
                "node": "harness",
                "status": mode,
                "summary": (
                    "DeepAgents package is importable; using bounded PatchSmith edit contract."
                    if package_available
                    else "DeepAgents package is not installed; using offline adapter compatibility mode."
                ),
                "framework": "deepagents",
            },
            {
                "node": "todo",
                "status": "completed",
                "summary": "Created repair todo from issue, retrieved context, and test command.",
                "todo_count": 3 if task.test_command else 2,
            },
            {
                "node": "context",
                "status": "completed",
                "summary": f"{len(task.retrieved_context)} retrieved contexts available to scaffold.",
                "context_paths": [context.path for context in task.retrieved_context],
            },
        ]
        plan = self.planner.plan(
            issue_text=task.issue_text,
            retrieved_context=task.retrieved_context,
        )
        plan_event: dict[str, Any] = {
            "node": "plan",
            "status": "completed" if plan else "no_match",
            "summary": (
                plan.summary if plan else "DeepAgents adapter produced no bounded repair plan."
            ),
        }
        metadata = _plan_or_planner_metadata(plan, self.planner)
        if metadata:
            plan_event["metadata"] = metadata
        trace.append(plan_event)
        if not plan:
            trace.append(
                {
                    "node": "review",
                    "status": "no_patch_generated",
                    "summary": "No patch candidate generated by DeepAgents adapter.",
                }
            )
            return _no_patch_result(
                task=task,
                generation_strategy="deepagents:no_plan",
                summary="DeepAgents adapter produced no bounded repair plan.",
                runtime_trace=trace,
            )
        try:
            result = _apply_plan(
                task=task,
                repo_path=repo_path,
                plan=plan,
                generation_strategy=f"deepagents:{plan.name}",
                risk_notes=[
                    "DeepAgents adapter uses PatchSmith's bounded text replacement safety gate.",
                    (
                        "Real deepagents package was available."
                        if package_available
                        else "Offline compatibility mode; install optional deepagents extra for live harness work."
                    ),
                    "Review before using outside controlled fixtures.",
                ],
                runtime_trace=[
                    *trace,
                    {"node": "edit", "status": "completed", "summary": f"Edited {plan.path}"},
                    {
                        "node": "review",
                        "status": "patch_generated",
                        "summary": "DeepAgents adapter generated one bounded patch candidate.",
                    },
                ],
            )
        except PatchSafetyError as error:
            trace.extend(
                [
                    {
                        "node": "edit",
                        "status": "failed",
                        "summary": str(error),
                    },
                    {
                        "node": "review",
                        "status": "no_patch_generated",
                        "summary": "Patch safety gate rejected DeepAgents adapter edit.",
                    },
                ]
            )
            return _no_patch_result(
                task=task,
                generation_strategy="deepagents:edit_failed",
                summary=str(error),
                runtime_trace=trace,
            )
        return result
