from __future__ import annotations

from importlib.util import find_spec
from pathlib import Path
from typing import Any

from patchsmith.patching import PatchSafetyError
from patchsmith.planning import HeuristicRepairPlanner, RepairPlanner
from patchsmith.runtime.core import (
    AgentResult,
    AgentTask,
    _apply_plan,
    _no_patch_result,
    _plan_for_task,
    _plan_or_planner_metadata,
)


class OpenAIAgentsRuntime:
    """Dependency-gated OpenAI Agents SDK adapter behind the runtime boundary.

    The `openai-agents` package is optional and imports as `agents`. Local seeded
    evals keep the same bounded planner/edit contract as the other runtimes so
    scaffold traces are comparable without credentials. Live model quality still
    belongs to the planner/provider calibration path.
    """

    def __init__(self, planner: RepairPlanner | None = None) -> None:
        self.planner = planner or HeuristicRepairPlanner()

    def run(self, task: AgentTask) -> AgentResult:
        repo_path = Path(task.repo_path)
        package_available = find_spec("agents") is not None
        mode = "package_available" if package_available else "compatibility_mode"
        trace: list[dict[str, Any]] = [
            {
                "node": "harness",
                "status": mode,
                "summary": (
                    "OpenAI Agents SDK is importable; using bounded PatchSmith edit contract."
                    if package_available
                    else (
                        "OpenAI Agents SDK is not installed; using offline adapter "
                        "compatibility mode."
                    )
                ),
                "framework": "openai_agents",
                "package": "openai-agents",
                "import_module": "agents",
            },
            {
                "node": "agent",
                "status": "configured",
                "summary": (
                    "Configured issue repair agent role, instructions, and handoff boundary."
                ),
                "tool_boundary": "patchsmith_bounded_edit_contract",
            },
            {
                "node": "guardrails",
                "status": "configured",
                "summary": (
                    "Repository paths and edit spans are validated before patch application."
                ),
            },
            {
                "node": "context",
                "status": "completed",
                "summary": f"{len(task.retrieved_context)} retrieved contexts available to agent.",
                "context_paths": [context.path for context in task.retrieved_context],
            },
        ]
        plan = _plan_for_task(self.planner, task)
        plan_event: dict[str, Any] = {
            "node": "plan",
            "status": "completed" if plan else "no_match",
            "summary": plan.summary if plan else "OpenAI Agents adapter produced no bounded plan.",
        }
        metadata = _plan_or_planner_metadata(plan, self.planner)
        if metadata:
            plan_event["metadata"] = metadata
        trace.append(plan_event)
        if not plan:
            trace.append(
                {
                    "node": "review",
                    "status": "no_patch_generated",
                    "summary": "No patch candidate generated by OpenAI Agents adapter.",
                }
            )
            return _no_patch_result(
                task=task,
                generation_strategy="openai_agents:no_plan",
                summary="OpenAI Agents adapter produced no bounded repair plan.",
                runtime_trace=trace,
            )
        try:
            return _apply_plan(
                task=task,
                repo_path=repo_path,
                plan=plan,
                generation_strategy=f"openai_agents:{plan.name}",
                risk_notes=[
                    (
                        "OpenAI Agents SDK adapter uses PatchSmith's bounded text "
                        "replacement safety gate."
                    ),
                    (
                        "Real openai-agents package was available."
                        if package_available
                        else (
                            "Offline compatibility mode; install optional openai-agents "
                            "extra for SDK harness work."
                        )
                    ),
                    "Review before using outside controlled fixtures.",
                ],
                runtime_trace=[
                    *trace,
                    {"node": "edit", "status": "completed", "summary": f"Edited {plan.path}"},
                    {
                        "node": "review",
                        "status": "patch_generated",
                        "summary": "OpenAI Agents adapter generated one bounded patch candidate.",
                    },
                ],
            )
        except PatchSafetyError as error:
            trace.extend(
                [
                    {
                        "node": "edit",
                        "status": "failed",
                        "summary": str(error),
                    },
                    {
                        "node": "review",
                        "status": "no_patch_generated",
                        "summary": "Patch safety gate rejected OpenAI Agents adapter edit.",
                    },
                ]
            )
            return _no_patch_result(
                task=task,
                generation_strategy="openai_agents:edit_failed",
                summary=str(error),
                runtime_trace=trace,
            )
